---
title: STAN CLARKE JR.
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Stan Clarke Jr., Web Developer
markdown: kramdown
