# Site settings
title: Stan Clarke Jr. | Web Developer
header-img: img/home-bg.jpg
email: sclarke.jr@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/stanclarke-jr.github.io"
url: "http://stanclarkejr.ca"
twitter_username: @stanclarkejr
github_username: stanclarke-jr
facebook_username: 
email_username:  sclarke.jr@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
